CREATE ROLE userdjango;
ALTER ROLE userdjango WITH NOSUPERUSER INHERIT CREATEROLE CREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'md511067dfd5efb6fa040976591229de061';

CREATE DATABASE django_base_crm_v3 WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';

ALTER DATABASE django_base_crm_v3 OWNER TO userdjango;